name: JSR Publish

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        
      - name: Commit changes
        run: |
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
           git add bun.lockb
           git add package.json
           git add jsr.json
           git commit -m "Commit lock file"

      - name: Publish to JSR
        run: bun x jsr publish
